### PR TITLE
fix static keybindings

### PR DESCRIPTION
**Pull request by dyphire**
fix that the keybindings in `input.conf` does not work if the options of static keybindings is empty.

### CODE REVIEW

**Comment by dyphire** [comment]
In fact, in my test, the specified keybindings usage of `add_key_binding` in this commit of https://github.com/jonniek/mpv-playlistmanager/commit/29e40b6c27b8840f97fcb4989ae15670c2bb8141 does not work at all.
I will add a new commit to fix it.

Edit: I found that this was due to I use `--no-input-default-bindings`: https://mpv.io/manual/master/#options-no-input-default-bindings. This binding multiple keys method to static keybinds is not reliable.

**Comment by dyphire** [comment]
~I am not satisfied with the current commit, because it allows the options of static keybindings to override the keybindings in the `input.conf`.~

~I think it is better to revert this commit of https://github.com/jonniek/mpv-playlistmanager/commit/29e40b6c27b8840f97fcb4989ae15670c2bb8141. @jonniek What do you think?~

Edit: This is will necessary for realize correct binding multiple keys to static keybinds.

**Comment by jonniek** [comment]
I'm having trouble understanding/reproducing this. Could you make some steps to reproduce like:

1. which settings to change from defaults, for example `dynamic_binds=no`
2. which command line options to use, for example `--no-input-default-bindings`
3. expected behavior
4. actual behavior

I haven't seen `--no-input-default-bindings` before. Looks pretty interesting. I suppose the usecase is for `input.conf` to contain all weak bindings explicitly. I don't think it's correct behavior for a script to always use forced binds, since it would make the `--no-input-default-bindings` meaningless.

~~I noticed one issue while testing with checking for nil but not empty string and made a commit for that. But it sounds unrelated to your issue since it's about no keybindings rather than multiple ones.~~

Edit: Ah sorry I didn't actually realize your PR addressed the above issue already. I was too focused on the change of weak binds to forced binds.

**Comment by dyphire** [comment]
> I noticed one issue while testing with checking for nil but not empty string and made a commit for that. But it sounds unrelated to your issue since it's about no keybindings rather than multiple ones.
>> fix that the keybindings in input.conf does not work if the options of static keybindings is empty.

This is exactly what this pr will do at first.

> I haven't seen `--no-input-default-bindings` before. Looks pretty interesting. I suppose the usecase is for `input.conf` to contain all weak bindings explicitly. I don't think it's correct behavior for a script to always use forced binds, since it would make the `--no-input-default-bindings` meaningless.

You're right, the `--no-input-default-bindings` is used  for `input.conf` to contain all weak bindings explicitly. Someone don't like messy management for keybindings.

The options of static keybindings will disable when use `--no-input-default-bindings`. This was expected before the implementation of binding multiple keys to static keybinds. Now it breaks this new function, so I modified pr to avoid it.

But I also don't like the implementation of forced binds. so I suggested revert this commit of https://github.com/jonniek/mpv-playlistmanager/commit/29e40b6c27b8840f97fcb4989ae15670c2bb8141 because it is not meaningful to implement binding multiple keys to static keybinds.
> I am not satisfied with the current commit, because it allows the options of static keybindings to override the keybindings in the `input.conf`.
I think it is better to revert this commit of https://github.com/jonniek/mpv-playlistmanager/commit/29e40b6c27b8840f97fcb4989ae15670c2bb8141. @jonniek What do you think?

**Comment by jonniek** [comment]
>The options of static keybindings will disable when use --no-input-default-bindings. This was expected before the implementation of binding multiple keys to static keybinds. Now it breaks this new function, so I modified pr to avoid it.

For me it still works as expected(with the new master), but maybe we are talking about different things when we say static keybinds.
Could you make the steps to reproduce, it would clarify a lot.

**Comment by dyphire** [comment]
> For me it still works as expected(with the new master), but maybe we are talking about different things when we say static keybinds. Could you make the steps to reproduce, it would clarify a lot.
1. set `no-input-default-bindings` in mpv.conf
2. set `F7 script-binding playlistmanager/showplaylist` in input.conf
3. set `key_showplaylist=n alt+s` in playlistmanager.conf

expected behavior since https://github.com/jonniek/mpv-playlistmanager/commit/29e40b6c27b8840f97fcb4989ae15670c2bb8141 should be to apply binding multiple keys to static keybinds.
actual behavior is only apply the keybindings in input.conf.
The actual behavior meets the expectations of `--no-input-default-bindings`, but maybe is not what the script of playlistmanager wants.

**Comment by jonniek** [comment]
I think that is the expected behavior.
It works the same way with single key binds.
I think the `input.conf` should take priority.

To make multiple bindings in `input.conf` when `key_showplaylist=` simply

```
n script-binding playlistmanager/showplaylist
alt+s script-binding playlistmanager/showplaylist
```

I think the README could use some more detailed explanation on keybinds. Especially the difference with weak and forced binds might be confusing to users.

**Comment by dyphire** [comment]
> I think that is the expected behavior.

That's good, because I also like this behavior.

I still don't like applying multiple keys to static binds. so I'm not positive about the modified pr.

Since what the pr want to do at first has been implemented by the commit of https://github.com/jonniek/mpv-playlistmanager/commit/26d743b34a68a6a9cb8e5449140a1d4cd2ff4d45, I decide to close it.

**Comment by jonniek** [comment]
It is optional though. If you wish you can define all keybindings as empty strings, and then do all the bindings from `input.conf`.

Thanks for making the PR though. I actually thought something had changed with keybinds in mpv but it was actually a bug in this script :+1:

**Comment by dyphire** [comment]
> It is optional though. If you wish you can define all keybindings as empty strings, and then do all the bindings from `input.conf`.

Yes, that's what I actually do for static binds.

**Comment by jonniek** [comment]
Oh actually the above doesn't work for dynamic keys, only the static ones. I'll update the README to have a bit more information about binds.

**Pull request closed without merging**
