### PR TITLE
Save video position before playback next file

### PR DESCRIPTION
**Pull request by GFDGIT**

### CODE REVIEW

**Comment by Silipwn** [comment]
@jonniek, the idea behind this was to save positions when you play next videos right? I was trying this with YouTube videos and noticed that the videos don't get saved.

**Comment by jonniek** [comment]
Pehaps you were jumping to specific files in the playlist, not the next file. I added the config writing to the branch where you jump to a specific file a631648

**Comment by Silipwn** [comment]
I still am not able to save the file position, (I've been using `< >` to switch files, could that be the issue?)
So if I switch videos, in the middle, the video resets and starts playing again. Is that intended? 
My idea was if I switch videos, it should save the position for where I was in the video.

(I can create an issue if required)

**Comment by jonniek** [comment]
Ah this doesn't ovewrite the native playlist controls. However, I could create a wrapper script message so that you could do this in `input.conf`
```
> script-message playlistmanager playlist-next
< script-message playlistmanager playlist-previous
```

**Comment by jonniek** [comment]
You can now do the above in aba6e2d631e1dfaa6326540a8b917126290417b0 and it will write the config

**Pull request merged**
